<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
	<Version>1.0.0</Version>
	<Deterministic>true</Deterministic>
	<IncludeSourceRevisionInInformationalVersion>true</IncludeSourceRevisionInInformationalVersion>
	<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

 <ItemGroup>
 	<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
 	<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
 	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
 	<PackageReference Include="Serilog" />
 	<PackageReference Include="Serilog.AspNetCore" />
 	<PackageReference Include="Serilog.Enrichers.CorrelationId" />
 	<PackageReference Include="Serilog.Sinks.Console" />
 	<PackageReference Include="Serilog.Sinks.File" />
 </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Devnet.Vault.Application\Devnet.Vault.Application.csproj" />
    <ProjectReference Include="..\Devnet.Vault.Domain\Devnet.Vault.Domain.csproj" />
    <ProjectReference Include="..\Devnet.Vault.Infrastructure\Devnet.Vault.Infrastructure.csproj" />
  </ItemGroup>

</Project>
