<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
  	<PackageReference Include="AWSSDK.S3" />
  	<PackageReference Include="Microsoft.EntityFrameworkCore" />
  	<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" PrivateAssets="all" />
  	<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  	<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
	<PackageReference Include="Serilog" />
	<PackageReference Include="StackExchange.Redis" />
	<PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Devnet.Vault.Application\Devnet.Vault.Application.csproj" />
    <ProjectReference Include="..\Devnet.Vault.Domain\Devnet.Vault.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Persistence\Migrations\" />
  </ItemGroup>

</Project>
